name: Update README on branch create

on:
  create:
    branches:
      - '*'

jobs:
  update-readme:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git global config
        run: |
          git config --global user.email "hamza.dabaghi@gmail.com"
          git config --global user.name "hamza dabaghi"
          git config --global user.username "hamzadabaghi"
      - name: Get the github token
        uses: actions/secret-manager@v0
        id: get_secret
        with:
          name: GT_TOKEN
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update README.md
        run: |
          branch_name=$(basename $GITHUB_REF)
          echo "- \`$branch_name\`" >> README.md
          git add README.md
          git commit -m "Updated README"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.get_secret.outputs.secret }}
